apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    deployment.kubernetes.io/revision: "6"
  creationTimestamp: 2019-07-31T09:34:40Z
  generation: 10
  labels:
    app: ys-nginx-web-server
  name: ys-nginx-web-server
  namespace: default
  resourceVersion: "18964"
  selfLink: /apis/apps/v1/namespaces/default/deployments/ys-nginx-web-server
  uid: 6bdb2f41-b376-11e9-ab61-42010a800183
spec:
  progressDeadlineSeconds: 600
  replicas: 2
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: ys-nginx-web-server
  strategy:
    rollingUpdate:
      maxSurge: 100%
      maxUnavailable: 100%
    type: RollingUpdate
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: ys-nginx-web-server
    spec:
      containers:
      - image: gcr.io/pe-training/semilexample@sha256:d2288d583435690adf84b0e5606ffa3bd7e9f6a77b668b4016274aa25190c2d8
        imagePullPolicy: IfNotPresent
        name: semil-nginx-sha256
        resources: {}
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
status:
  availableReplicas: 2
  conditions:
  - lastTransitionTime: 2019-07-31T10:18:47Z
    lastUpdateTime: 2019-07-31T10:18:47Z
    message: Deployment has minimum availability.
    reason: MinimumReplicasAvailable
    status: "True"
    type: Available
  - lastTransitionTime: 2019-07-31T09:34:40Z
    lastUpdateTime: 2019-07-31T11:03:45Z
    message: ReplicaSet "ys-nginx-web-server-c5f479c68" has successfully progressed.
    reason: NewReplicaSetAvailable
    status: "True"
    type: Progressing
  observedGeneration: 10
  readyReplicas: 2
  replicas: 2
  updatedReplicas: 2

